version: "1"
rules:
  - base: master
    upstream: flightlessmango:master
    mergeMethod: merge
    mergeUnstable: false
    assignees:
      - KyleGospo
    reviewers:
      - KyleGospo
    conflictReviewers:
      - KyleGospo
